//
//  FetchedTranscript.swift
//  YouTubeTranscript
//
//  Created by David Sherlock on 2025.
//

import Foundation

/// The result of fetching a transcript, containing segments and optional metadata.
///
/// ```swift
/// let result = try await YouTubeTranscript.fetch("dQw4w9WgXcQ")
///
/// print(result.plainText)
/// print(result.video?.title ?? "Unknown")
/// print(result.formattedDuration) // "3:32"
/// print(result.typeLabel)         // "auto" or "manual"
///
/// for segment in result.segments {
///     print("[\(segment.formattedStart)] \(segment.text)")
/// }
/// ```
public struct FetchedTranscript: Sendable {

    /// The video ID this transcript belongs to.
    public let videoId: String

    /// The transcript segments with timing information.
    public let segments: [TranscriptSegment]

    /// Video metadata (title, author, views, description, etc.).
    ///
    /// Extracted from the same API call as the transcript at no extra cost.
    /// May be `nil` if YouTube's response structure changes.
    public let video: VideoMetadata?

    /// The language code of the fetched transcript (e.g., `"en"`).
    public let language: String

    /// Whether this transcript was auto-generated by YouTube's speech recognition.
    public let isGenerated: Bool

    /// All segment text joined into a single string, separated by spaces.
    public var plainText: String {
        segments.map(\.text).joined(separator: " ")
    }

    /// Total duration of the transcript in seconds.
    ///
    /// Calculated from the last segment's start time plus its duration.
    public var duration: Double {
        guard let last = segments.last else { return 0 }
        return last.start + last.duration
    }

    /// Number of segments in the transcript.
    public var count: Int {
        segments.count
    }

    /// A human-readable label for the transcript type: `"manual"` or `"auto"`.
    public var typeLabel: String {
        isGenerated ? "auto" : "manual"
    }

    /// The total duration formatted as `"M:SS"` or `"H:MM:SS"`.
    public var formattedDuration: String {
        TranscriptSegment.formatTimestamp(duration)
    }

    /// The full transcript with timestamps, one segment per line.
    ///
    /// ```
    /// [0:00] Hello everyone
    /// [0:02] Welcome to my video
    /// ```
    public var timestampedText: String {
        segments.map { "[\($0.formattedStart)] \($0.text)" }.joined(separator: "\n")
    }
}
