//
//  TranscriptTrack.swift
//  YouTubeTranscript
//
//  Created by David Sherlock on 2025.
//

import Foundation

/// Represents an available transcript track for a video.
///
/// Use ``YouTubeTranscript/list(_:)`` to discover available tracks
/// before fetching.
///
/// ```swift
/// for track in list.tracks {
///     print("\(track.language) (\(track.languageCode)) — \(track.typeLabel)")
/// }
/// ```
public struct TranscriptTrack: Codable, Equatable, Sendable {

    /// The language code (e.g., `"en"`, `"de"`, `"ja"`).
    public let languageCode: String

    /// The human-readable language name (e.g., `"English"`, `"German"`).
    public let language: String

    /// Whether this transcript was auto-generated by YouTube's speech recognition.
    ///
    /// When `true`, the transcript is from ASR (Automatic Speech Recognition).
    /// When `false`, it was manually created or uploaded by the video creator.
    public let isGenerated: Bool

    /// Whether this transcript supports translation to other languages.
    public let isTranslatable: Bool

    /// The base URL for fetching the transcript content.
    internal let baseUrl: String

    /// Internal memberwise initializer.
    internal init(languageCode: String, language: String, isGenerated: Bool, isTranslatable: Bool, baseUrl: String) {
        self.languageCode = languageCode
        self.language = language
        self.isGenerated = isGenerated
        self.isTranslatable = isTranslatable
        self.baseUrl = baseUrl
    }

    /// A human-readable label for the transcript type: `"manual"` or `"auto"`.
    public var typeLabel: String {
        isGenerated ? "auto" : "manual"
    }

    // Exclude internal baseUrl from Codable
    private enum CodingKeys: String, CodingKey {
        case languageCode, language, isGenerated, isTranslatable
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        languageCode = try container.decode(String.self, forKey: .languageCode)
        language = try container.decode(String.self, forKey: .language)
        isGenerated = try container.decode(Bool.self, forKey: .isGenerated)
        isTranslatable = try container.decode(Bool.self, forKey: .isTranslatable)
        baseUrl = ""
    }
}

/// The result of listing available transcripts for a video.
///
/// Provides convenience methods for finding tracks by language and
/// filtering between manual and auto-generated transcripts.
///
/// ```swift
/// let list = try await YouTubeTranscript.list("dQw4w9WgXcQ")
///
/// for track in list.tracks {
///     print("\(track.language) (\(track.languageCode)) — \(track.typeLabel)")
/// }
///
/// if let german = list.findTrack(languages: ["de"]) {
///     print("German transcript available")
/// }
/// ```
public struct TranscriptList: Sendable {

    /// The video ID these transcripts belong to.
    public let videoId: String

    /// All available transcript tracks.
    public let tracks: [TranscriptTrack]

    /// Manually created transcript tracks only.
    public var manualTracks: [TranscriptTrack] {
        tracks.filter { !$0.isGenerated }
    }

    /// Auto-generated (ASR) transcript tracks only.
    public var generatedTracks: [TranscriptTrack] {
        tracks.filter { $0.isGenerated }
    }

    /// Language codes for all available tracks.
    public var availableLanguages: [String] {
        tracks.map(\.languageCode)
    }

    /// Finds the best matching track for the given language preferences.
    ///
    /// Manually created transcripts are always preferred over auto-generated
    /// ones for the same language. Languages are tried in order of priority.
    ///
    /// - Parameter languages: Language codes in descending priority (e.g., `["en", "de"]`).
    /// - Returns: The best matching track, or `nil` if no match is found.
    public func findTrack(languages: [String] = ["en"]) -> TranscriptTrack? {
        for lang in languages {
            // Prefer manual tracks
            if let track = manualTracks.first(where: { $0.languageCode == lang }) {
                return track
            }
            // Then auto-generated
            if let track = generatedTracks.first(where: { $0.languageCode == lang }) {
                return track
            }
            // Try prefix match (e.g., "en" matches "en-US")
            if let track = (manualTracks + generatedTracks).first(where: { $0.languageCode.hasPrefix(lang) }) {
                return track
            }
        }
        return nil
    }
}
